use std::env;
use std::fs::File;
use std::fs::OpenOptions;
use std::fs::{self};
use std::io::Write;
use std::path::Path;
use std::path::PathBuf;

macro_rules! log {
    ($($tokens: tt)*) => {
        {
            let msg = format!($($tokens)*);
                        println!("cargo::warning={}", msg);

            if let Ok(mut file) = OpenOptions::new()
                .create(true)
                .append(true)
                .open("build.log") {
                let _ = writeln!(file, "{}", msg);
                let _ = file.flush();
            }
        }
    }
}

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();

    generate_teb_asm(&out_dir);

    generate_winapi_bindings(&out_dir);

    println!("cargo:rerun-if-changed=build.rs");
}

fn generate_teb_asm(out_dir: &str) {
    let dest_path = Path::new(out_dir).join("teb_asm.rs");

    let code = {
        #[cfg(feature = "obfuscation")]
        {
            use mfa::interpreter::Compile;
            use mfa::interpreter::Intrepreter;

            let expr = "(a ^ b) - c + (z - x)";

            let defs_path = Path::new(out_dir).join("defs.txt");
            let mut file = File::create(&defs_path).unwrap();
            writeln!(file, "a = 100\nb = 83\nc = 7\nz = 2\nx = 2\ny = 1").unwrap();

            let result = Intrepreter::from_source(expr, 1, false);

            match result {
                Ok((_, obfuscated)) => {
                    format!(
                        r#"// Auto-generated by build.rs

#[inline(never)]
pub unsafe fn get_teb() -> *mut TEB {{
    let a: isize = 100;
    let b: isize = 83;
    let c: isize = 7;
    let z: isize = 2;
    let x: isize = 2;
unsafe{{

    std::hint::black_box(
        crate::utils::readqgsword(
            std::hint::black_box(({}) as usize)
        )
    ) as *mut TEB
}}
}}
"#,
                        obfuscated
                    )
                }
                Err(e) => panic!("Failed to parse expression: {}", e),
            }
        }

        #[cfg(not(feature = "obfuscation"))]
        {
            format!(
                r#"// Auto-generated by build.rs

#[inline(never)]
pub unsafe fn get_teb() -> *mut TEB {{
unsafe{{
    crate::utils::readqgsword(0x30) as *mut TEB

}}
}}
"#
            )
        }
    };

    fs::write(&dest_path, code).unwrap();
}

fn generate_winapi_bindings(out_dir: &str) {
    let windows_sdk = r"C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um";

    log!("Starting WinAPI bindings generation...");

    let bindings = bindgen::Builder::default()
        .header_contents(
            "wrapper.h",
            r#"
            #include <windows.h>
            #include <tlhelp32.h>
            #include <psapi.h>
            #include <winuser.h>
        "#,
        )
        .clang_arg(format!("-I{}", windows_sdk))
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .allowlist_function(".*")
        .allowlist_type("PROCESSENTRY32.*")
        .allowlist_type("TEB")
        .allowlist_type("PEB")
        .blocklist_type("_?P?IMAGE_TLS_DIRECTORY.*")
        .generate()
        .expect("Unable to generate bindings");

    let raw_bindings_path = PathBuf::from(out_dir).join("raw_bindings.rs");
    bindings
        .write_to_file(&raw_bindings_path)
        .expect("Couldn't write raw bindings!");

    log!("Raw bindings written successfully");

    generate_wrapped_bindings(&raw_bindings_path, out_dir);
}

fn generate_wrapped_bindings(raw_path: &PathBuf, out_dir: &str) {
    use syn::ForeignItem;
    use syn::Item;

    log!("Parsing generated bindings...");

    let content = std::fs::read_to_string(raw_path).unwrap();
    let file = syn::parse_file(&content).unwrap();

    // Count total functions
    let total_functions: usize = file
        .items
        .iter()
        .filter_map(|item| {
            if let Item::ForeignMod(foreign_mod) = item {
                Some(
                    foreign_mod
                        .items
                        .iter()
                        .filter(|i| matches!(i, ForeignItem::Fn(_)))
                        .count(),
                )
            } else {
                None
            }
        })
        .sum();

    log!("Found {} functions to wrap", total_functions);

    let wrapped_path = PathBuf::from(out_dir).join("winapi_bindings.rs");
    let mut output = File::create(&wrapped_path).unwrap();

    writeln!(output, "// Auto-generated wrapped Windows API bindings").unwrap();
    writeln!(output).unwrap();
    writeln!(output, "#[cfg(feature = \"obfuscation\")]").unwrap();
    writeln!(output, "use crate::runtime::pe64_runtime::PE64Runtime;").unwrap();
    writeln!(output).unwrap();

    let mut processed = 0;
    let mut succeeded = 0;
    let mut failed_funcs = Vec::new();

    for item in file.items {
        if let Item::ForeignMod(foreign_mod) = item {
            for foreign_item in foreign_mod.items {
                if let ForeignItem::Fn(func) = foreign_item {
                    processed += 1;
                    let func_name = func.sig.ident.to_string();

                    // Log every 10 functions
                    if processed % 10 == 0 {
                        let percentage =
                            (processed as f32 / total_functions as f32 * 100.0) as usize;
                        log!(
                            "[{}/{}] {}% - Processing: {}",
                            processed,
                            total_functions,
                            percentage,
                            func_name
                        );
                    }

                    match generate_wrapper(&mut output, &func) {
                        Ok(_) => succeeded += 1,
                        Err(e) => {
                            failed_funcs.push((func_name.clone(), e.to_string()));
                        }
                    }
                }
            }
        }
    }

    log!("========================================");
    log!("Binding generation complete!");
    log!("  Total:     {}", total_functions);
    log!("  Succeeded: {}", succeeded);
    log!("  Failed:    {}", failed_funcs.len());
    log!("========================================");

    if !failed_funcs.is_empty() {
        log!("Failed functions:");
        for (name, err) in failed_funcs.iter().take(5) {
            log!("  - {}: {}", name, err);
        }
        if failed_funcs.len() > 5 {
            log!("  ... and {} more", failed_funcs.len() - 5);
        }
    }

    println!(
        "cargo::warning={}",
        format!("Finished creating bindings... now wait for rustc to compile all the crap :)")
    );
}

fn generate_wrapper(output: &mut File, func: &syn::ForeignItemFn) -> std::io::Result<()> {
    let name = &func.sig.ident;
    let inputs = &func.sig.inputs;
    let ret = &func.sig.output;

    let dll = guess_dll(&name.to_string());

    let mut arg_names = Vec::new();
    let mut arg_decls = Vec::new();
    let mut arg_types = Vec::new();

    for (i, input) in inputs.iter().enumerate() {
        if let syn::FnArg::Typed(pat_type) = input {
            let arg_name = if let syn::Pat::Ident(ident) = &*pat_type.pat {
                ident.ident.to_string()
            } else {
                format!("arg{}", i)
            };

            let arg_type = &pat_type.ty;

            arg_names.push(arg_name.clone());
            arg_decls.push(format!("{}: {}", arg_name, type_to_string(arg_type)));
            arg_types.push(type_to_string(arg_type));
        }
    }

    let arg_names_str = arg_names.join(", ");
    let args_decl_str = arg_decls.join(", ");
    let fn_type_args_str = arg_types.join(", ");

    let return_type_str = match ret {
        syn::ReturnType::Default => "()".to_string(),
        syn::ReturnType::Type(_, ty) => type_to_string(ty),
    };

    let return_annotation = if return_type_str == "()" {
        String::new()
    } else {
        format!("-> {}", return_type_str)
    };

    // Normal version
    writeln!(output, "#[cfg(not(feature = \"obfuscation\"))]")?;
    writeln!(output, "#[inline]")?;
    writeln!(
        output,
        "pub unsafe fn {}({}) {} {{",
        name, args_decl_str, return_annotation
    )?;
    writeln!(output, "    super::raw::{}({})", name, arg_names_str)?;
    writeln!(output, "}}")?;
    writeln!(output)?;

    // Obfuscated version
    writeln!(output, "#[cfg(feature = \"obfuscation\")]")?;
    writeln!(
        output,
        "pub unsafe fn {}({}) {} {{",
        name, args_decl_str, return_annotation
    )?;
    writeln!(
        output,
        "    type FnType = unsafe extern \"system\" fn({}) -> {};",
        fn_type_args_str, return_type_str
    )?;
    writeln!(output)?;
    writeln!(output, "    static mut FN_PTR: Option<FnType> = None;")?;
    writeln!(
        output,
        "    static INIT: std::sync::Once = std::sync::Once::new();"
    )?;
    writeln!(output)?;
    writeln!(output, "    INIT.call_once(|| {{")?;
    writeln!(
        output,
        "        if let Ok(module) = PE64Runtime::from_module(\"{}\") {{",
        dll
    )?;
    writeln!(
        output,
        "            if let Some(export) = module.find_export(\"{}\") {{",
        name
    )?;
    writeln!(
        output,
        "                FN_PTR = Some(core::mem::transmute(export.func_addr as usize));"
    )?;
    writeln!(output, "            }}")?;
    writeln!(output, "        }}")?;
    writeln!(output, "    }});")?;
    writeln!(output)?;
    writeln!(
        output,
        "    FN_PTR.expect(\"Failed to load {}\")({})",
        name, arg_names_str
    )?;
    writeln!(output, "}}")?;
    writeln!(output)?;

    Ok(())
}

fn type_to_string(ty: &syn::Type) -> String {
    match ty {
        syn::Type::Path(type_path) => type_path
            .path
            .segments
            .iter()
            .map(|seg| seg.ident.to_string())
            .collect::<Vec<_>>()
            .join("::"),
        syn::Type::Ptr(type_ptr) => {
            let mutability = if type_ptr.mutability.is_some() {
                "mut "
            } else {
                "const "
            };
            format!("*{}{}", mutability, type_to_string(&type_ptr.elem))
        }
        syn::Type::Reference(type_ref) => {
            let mutability = if type_ref.mutability.is_some() {
                "mut "
            } else {
                ""
            };
            let lifetime = type_ref
                .lifetime
                .as_ref()
                .map(|lt| format!("{} ", lt.ident))
                .unwrap_or_default();
            format!(
                "&{}{}{}",
                lifetime,
                mutability,
                type_to_string(&type_ref.elem)
            )
        }
        syn::Type::Array(type_array) => {
            format!(
                "[{}; {}]",
                type_to_string(&type_array.elem),
                quote::quote!(#type_array.len).to_string()
            )
        }
        syn::Type::Tuple(type_tuple) => {
            if type_tuple.elems.is_empty() {
                "()".to_string()
            } else {
                let elems = type_tuple
                    .elems
                    .iter()
                    .map(type_to_string)
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("({})", elems)
            }
        }
        _ => quote::quote!(#ty).to_string(),
    }
}

fn guess_dll(func_name: &str) -> &'static str {
    let name_lower = func_name.to_lowercase();

    if name_lower.contains("process")
        || name_lower.contains("thread")
        || name_lower.contains("library")
        || name_lower.contains("module")
        || name_lower.contains("toolhelp")
        || name_lower.contains("heap")
        || name_lower.contains("virtual")
        || name_lower.contains("createfile")
    {
        "KERNEL32.DLL"
    } else if name_lower.contains("window")
        || name_lower.contains("message")
        || name_lower.contains("dialog")
        || name_lower.contains("menu")
    {
        "USER32.DLL"
    } else if name_lower.contains("reg")
        || name_lower.contains("security")
        || name_lower.contains("service")
    {
        "ADVAPI32.DLL"
    } else if name_lower.contains("gdi")
        || name_lower.contains("bitmap")
        || name_lower.contains("brush")
    {
        "GDI32.DLL"
    } else if name_lower.contains("shell") || name_lower.contains("shget") {
        "SHELL32.DLL"
    } else {
        "KERNEL32.DLL"
    }
}
