use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("teb_asm.rs");

    let code = {
        #[cfg(feature = "obfuscation")]
        {
            use mfa::interpreter::Compile;
            use mfa::interpreter::Intrepreter;
            use std::fs::File;
            use std::io::Write;

            let expr = "(a ^ b) - c + (z - x)";

            let defs_path = Path::new(&out_dir).join("defs.txt");
            let mut file = File::create(&defs_path).unwrap();
            writeln!(file, "a = 100\nb = 83\nc = 7\nz = 2\nx = 2\ny = 1").unwrap();

            let result = Intrepreter::from_source(expr, 1, false);

            match result {
                Ok((_, obfuscated)) => {
                    println!("cargo:rerun-if-changed=build.rs");

                    format!(
                        r#"// Auto-generated by build.rs

#[inline(never)]
pub unsafe fn get_teb() -> *mut TEB {{
    let a: isize = 100;
    let b: isize = 83;
    let c: isize = 7;
    let z: isize = 2;
    let x: isize = 2;
unsafe{{

    std::hint::black_box(
        crate::utils::readqgsword(
            std::hint::black_box(({}) as usize)
        )
    ) as *mut TEB
}}
}}
"#,
                        obfuscated
                    )
                }
                Err(e) => panic!("Failed to parse expression: {}", e),
            }
        }

        #[cfg(not(feature = "obfuscation"))]
        {
            format!(
                r#"// Auto-generated by build.rs

#[inline(never)]
pub unsafe fn get_teb() -> *mut TEB {{
unsafe{{
    crate::utils::readqgsword(0x30) as *mut TEB

}}
}}
"#
            )
        }
    };

    fs::write(&dest_path, code).unwrap();
}
