use std::env;
use std::ffi::OsString;
use std::fs::File;
use std::fs::OpenOptions;
use std::fs::{self};
use std::io::Write;
use std::path::Path;
use std::path::PathBuf;

macro_rules! log {
    ($($tokens: tt)*) => {
        {
            let msg = format!($($tokens)*);

            if let Ok(mut file) = OpenOptions::new()
                .create(true)
                .append(true)
                .open("build.log") {
                let _ = writeln!(file, "{}", msg);
                let _ = file.flush();
            }
        }
    }
}

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();

    generate_teb_asm(&out_dir);

    generate_winapi_bindings(&out_dir);

    println!("cargo:rerun-if-changed=build.rs");
}

fn generate_teb_asm(out_dir: &str) {
    let dest_path = Path::new(out_dir).join("teb_asm.rs");

    let code = {
        {
            use mfa::interpreter::Compile;
            use mfa::interpreter::Intrepreter;

            let expr = "(a ^ b) - c + (z - x)";

            let defs_path = Path::new(out_dir).join("defs.txt");
            let mut file = File::create(&defs_path).unwrap();
            writeln!(file, "a = 100\nb = 83\nc = 7\nz = 2\nx = 2\ny = 1").unwrap();

            let result = Intrepreter::from_source(expr, 1, false);

            match result {
                Ok((_, obfuscated)) => {
                    format!(
                        r#"// Auto-generated by build.rs

#[inline(never)]
pub unsafe fn get_teb() -> *mut TEB {{
    let a: isize = 100;
    let b: isize = 83;
    let c: isize = 7;
    let z: isize = 2;
    let x: isize = 2;
unsafe{{

    std::hint::black_box(
        crate::utils::readqgsword(
            std::hint::black_box(({}) as usize)
        )
    ) as *mut TEB
}}
}}
"#,
                        obfuscated
                    )
                }
                Err(e) => panic!("Failed to parse expression: {}", e),
            }
        }
    };

    fs::write(&dest_path, code).unwrap();
}

#[cfg(windows)]
fn windows_kits_root10() -> PathBuf {
    use winreg::RegKey;
    use winreg::enums::HKEY_LOCAL_MACHINE;

    let hklm = RegKey::predef(HKEY_LOCAL_MACHINE);

    // Common locations for KitsRoot10. KitsRoot10 value typically includes trailing
    // backslash. [web:7][web:17]
    let candidates = [
        r"SOFTWARE\Microsoft\Windows Kits\Installed Roots",
        r"SOFTWARE\WOW6432Node\Microsoft\Windows Kits\Installed Roots",
    ];

    for key_path in candidates {
        if let Ok(key) = hklm.open_subkey(key_path) {
            if let Ok(dir) = key.get_value::<String, _>("KitsRoot10") {
                return PathBuf::from(dir);
            }
        }
    }

    panic!(
        r#"Windows SDK not found: registry value KitsRoot10 missing.
Looked in HKLM\SOFTWARE\Microsoft\Windows Kits\Installed Roots (and WOW6432Node)."#
    );
}

#[cfg(not(windows))]
fn windows_kits_root10() -> PathBuf {
    let project_dir = env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".to_string());
    PathBuf::from(project_dir).join("windows-kit")
}

#[cfg(windows)]
fn newest_windows_sdk_include_dir(kits_root10: &Path) -> PathBuf {
    let include_root = kits_root10.join("Include");
    let rd = fs::read_dir(&include_root).unwrap_or_else(|e| {
        panic!(
            "Windows SDK include root not found: {:?} ({})",
            include_root, e
        )
    });

    // Pick the newest version folder by lexicographic sort
    let mut versions: Vec<OsString> = rd
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().ok().map(|t| t.is_dir()).unwrap_or(false))
        .map(|e| e.file_name())
        .collect();

    versions.sort();
    versions.reverse();

    for ver in versions {
        let base = include_root.join(&ver);
        let um = base.join("um");
        let shared = base.join("shared");
        let ucrt = base.join("ucrt");

        if um.is_dir() && shared.is_dir() && ucrt.is_dir() {
            return base;
        }
    }

    panic!(
        "No Windows SDK Include/<version> directory contained um/shared/ucrt under {:?}",
        include_root
    );
}

#[cfg(not(windows))]
fn newest_windows_sdk_include_dir(kits_root10: &Path) -> PathBuf {
    let include_root = kits_root10.join("sdk").join("include");
    log!("Using local xwin include dir: {:?}", include_root);

    if !include_root.exists() {
        panic!("Windows SDK include root not found: {:?}", include_root);
    }

    include_root
}

fn generate_winapi_bindings(out_dir: &str) {
    log!("Starting WinAPI bindings generation...");

    let kits = windows_kits_root10();
    let include_ver = newest_windows_sdk_include_dir(&kits);

    log!("Found WINAPI version: {:?}", &include_ver);

    let target = env::var("TARGET").unwrap_or_else(|_| "x86_64-pc-windows-msvc".to_string());
    let is_64_bit = target.contains("x86_64") || target.contains("aarch64");

    let mut bindings_builder = bindgen::Builder::default()
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .header_contents(
            "wrapper.h",
            r#"
#define PHNT_MODE PHNT_MODE_USER
#define PHNT_VERSION PHNT_WINDOWS_11
#define _WIN32_WINNT 0x0A00
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#define WINNT_NO_DEPRECATE

#include <phnt_windows.h>
#include <phnt.h>
#include <ntpsapi.h>
#include <ntpebteb.h>
#include <tlhelp32.h>
#include <psapi.h>
#include <winuser.h>
"#,
        )
        .clang_arg("-fms-compatibility")
        .clang_arg("-fms-extensions")
        .clang_arg(format!("--target={}", target))
        .allowlist_recursively(true)
        .allowlist_type(".*")
        .allowlist_function(".*")
        .blocklist_type("winternl.*")
        .layout_tests(false)
        .generate_comments(false);

    if is_64_bit {
        bindings_builder = bindings_builder.clang_arg("-D_WIN64");
    }

    #[cfg(not(windows))]
    {
        // IMPORTANT: phnt must come FIRST to override incomplete Windows SDK
        // definitions
        bindings_builder = bindings_builder
            .clang_arg("-I./phnt".to_string())
            .clang_arg(format!("-I{}", kits.join("crt").join("include").display()))
            .clang_arg(format!("-I{}", include_ver.join("ucrt").display()))
            .clang_arg(format!("-I{}", include_ver.join("shared").display()))
            .clang_arg(format!("-I{}", include_ver.join("um").display()));
    }

    #[cfg(windows)]
    {
        bindings_builder = bindings_builder.clang_arg("-I./phnt".to_string());
    }

    let bindings = bindings_builder
        .generate()
        .expect("Unable to generate bindings");

    let raw_bindings_path = PathBuf::from(out_dir).join("raw_bindings.rs");
    bindings
        .write_to_file(&raw_bindings_path)
        .expect("Couldn't write raw bindings!");

    log!("Post-processing raw bindings...");

    // Fix extern blocks to be unsafe
    let content = std::fs::read_to_string(&raw_bindings_path).unwrap();
    let fixed_content = content
        .lines()
        .map(|line| {
            let trimmed = line.trim_start();
            if trimmed.starts_with("extern \"") && trimmed.ends_with('{') {
                let indent = &line[..line.len() - trimmed.len()];
                format!("{indent}unsafe {trimmed}")
            } else {
                line.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("\n");

    std::fs::write(&raw_bindings_path, fixed_content).unwrap();

    log!("Raw bindings written and fixed");

    generate_wrapped_bindings(&raw_bindings_path, out_dir);
}

fn generate_wrapped_bindings(raw_path: &PathBuf, out_dir: &str) {
    let limit: Option<usize> = None;
    use syn::ForeignItem;
    use syn::Item;

    log!("Parsing generated bindings...");

    let content = std::fs::read_to_string(raw_path).unwrap();
    let file = syn::parse_file(&content).unwrap();

    let wrapped_path = PathBuf::from(out_dir).join("winapi_bindings.rs");
    let mut output = File::create(&wrapped_path).unwrap();

    writeln!(output, "// Auto-generated wrapped Windows API bindings").unwrap();
    writeln!(output).unwrap();

    // Just include the raw bindings - this gives you ALL types as-is
    writeln!(
        output,
        "#[allow(warnings,non_snake_case, non_camel_case_types, non_upper_case_globals, dead_code, unnecessary_transmutes,unsafe_op_in_unsafe_fn)]"
    ).unwrap();

    writeln!(output, "pub mod raw {{").unwrap();
    writeln!(
        output,
        "    include!(concat!(env!(\"OUT_DIR\"), \"/raw_bindings.rs\"));"
    )
    .unwrap();
    writeln!(output, "}}").unwrap();
    writeln!(output).unwrap();

    // todo: figure out a way to only reexport types
    writeln!(output, "pub use raw::*;").unwrap();

    writeln!(output).unwrap();

    writeln!(
        output,
        "#[cfg(any(feature = \"obfuscation\", feature = \"hells_gate\"))]"
    )
    .unwrap();
    writeln!(
        output,
        "use crate::runtime::NativePeRuntime as NativePERuntime;"
    )
    .unwrap();
    writeln!(output, "use crate::utils::to_wide;").unwrap();

    writeln!(output).unwrap();

    // Count functions
    let total_functions: usize = file
        .items
        .iter()
        .filter_map(|item| {
            if let Item::ForeignMod(fm) = item {
                Some(
                    fm.items
                        .iter()
                        .filter(|i| matches!(i, ForeignItem::Fn(_)))
                        .count(),
                )
            } else {
                None
            }
        })
        .sum();

    let target_count = limit.unwrap_or(total_functions);
    log!("Found {} total functions", total_functions);
    if let Some(n) = limit {
        log!("Generating wrappers for first {} functions", n);
    }

    // Only generate function wrappers
    let mut processed = 0;
    let mut succeeded = 0;
    let mut failed_funcs = Vec::new();

    'outer: for item in file.items {
        if let Item::ForeignMod(foreign_mod) = item {
            for foreign_item in foreign_mod.items {
                if let ForeignItem::Fn(func) = foreign_item {
                    if let Some(max) = limit
                        && processed >= max
                    {
                        break 'outer;
                    }

                    processed += 1;
                    let func_name = func.sig.ident.to_string();

                    if processed % 10 == 0 {
                        let percentage = (processed as f32 / target_count as f32 * 100.0) as usize;
                        log!(
                            "[{}/{}] {}% - {}",
                            processed,
                            target_count,
                            percentage,
                            func_name
                        );
                    }

                    match generate_wrapper(&mut output, &func) {
                        Ok(_) => succeeded += 1,
                        Err(e) => failed_funcs.push((func_name.clone(), e.to_string())),
                    }
                }
            }
        }
    }

    log!("========================================");
    log!("Binding generation complete!");
    log!("  Functions wrapped: {}", succeeded);
    log!("  Functions failed:  {}", failed_funcs.len());
    log!("========================================");

    log!("Now we wait for rustc to compile thew few thousand function and structs...");
    if !failed_funcs.is_empty() {
        log!("Failed functions:");
        for (name, err) in failed_funcs.iter().take(5) {
            log!("  - {}: {}", name, err);
        }
        if failed_funcs.len() > 5 {
            log!("  ... and {} more", failed_funcs.len() - 5);
        }
    }
}

fn generate_wrapper(output: &mut File, func: &syn::ForeignItemFn) -> std::io::Result<()> {
    let name = &func.sig.ident;
    let func_name = name.to_string();

    let inputs = &func.sig.inputs;
    let ret = &func.sig.output;

    let dll = guess_dll(&func_name);

    let mut arg_names = Vec::new();
    let mut arg_decls = Vec::new();
    let mut arg_types = Vec::new();

    for (i, input) in inputs.iter().enumerate() {
        if let syn::FnArg::Typed(pat_type) = input {
            let arg_name = if let syn::Pat::Ident(ident) = &*pat_type.pat {
                ident.ident.to_string()
            } else {
                format!("arg{}", i)
            };

            let arg_type = &pat_type.ty;

            arg_names.push(arg_name.clone());
            arg_decls.push(format!("{}: {}", arg_name, type_to_string(arg_type)));
            arg_types.push(type_to_string(arg_type));
        }
    }

    let arg_names_str = arg_names.join(", ");
    let args_decl_str = arg_decls.join(", ");
    let fn_type_args_str = arg_types.join(", ");

    let return_type_str = match ret {
        syn::ReturnType::Default => "()".to_string(),
        syn::ReturnType::Type(_, ty) => type_to_string(ty),
    };

    let return_annotation = if return_type_str == "()" {
        String::new()
    } else {
        format!("-> {}", return_type_str)
    };

    // Generate the main function wrapper
    generate_single_wrapper(
        output,
        &func_name,
        None, // No alias, use func_name
        &args_decl_str,
        &return_annotation,
        &arg_names_str,
        &fn_type_args_str,
        &return_type_str,
        dll,
    )?;

    // If function starts with K32, also generate non-K32 alias
    if func_name.starts_with("K32") {
        let alias_name = func_name.strip_prefix("K32").unwrap();
        writeln!(output, "// Compatibility alias for {}", alias_name)?;
        generate_single_wrapper(
            output,
            alias_name,
            Some(&func_name), // Use K32 name as the real function
            &args_decl_str,
            &return_annotation,
            &arg_names_str,
            &fn_type_args_str,
            &return_type_str,
            dll,
        )?;
    }

    #[cfg(feature = "hells_gate")]
    if func_name.starts_with("Nt") || func_name.starts_with("Zw") {
        let alias_name = format!("{}HellsGate", &func_name);
        generate_single_wrapper_hells_gate(
            output,
            &alias_name,
            Some(&func_name), // Use K32 name as the real function
            &args_decl_str,
            &return_annotation,
            &arg_names_str,
            &fn_type_args_str,
            &return_type_str,
            dll,
        )?;
    }

    Ok(())
}
#[cfg(feature = "hells_gate")]
fn generate_single_wrapper_hells_gate(
    output: &mut File,
    name: &str,
    real_func_name: Option<&str>,
    args_decl_str: &str,
    return_annotation: &str,
    arg_names_str: &str,
    _fn_type_args_str: &str, // Unused in Hell's Gate but kept for API compatibility
    return_type_str: &str,
    dll: &str,
) -> std::io::Result<()> {
    let target_func = real_func_name.unwrap_or(name);

    // Normal version (No change - still calls standard API)
    writeln!(output, "#[cfg(not(feature = \"hells_gate\"))]")?;
    writeln!(output, "#[inline]")?;
    writeln!(
        output,
        "pub unsafe fn {}({}) {} {{",
        name, args_decl_str, return_annotation
    )?;
    writeln!(
        output,
        "    unsafe {{ raw::{}({}) }} ",
        target_func, arg_names_str
    )?;
    writeln!(output, "}}")?;
    writeln!(output)?;

    // Hell's Gate version
    writeln!(output, "#[cfg(feature = \"hells_gate\")]")?;
    writeln!(
        output,
        "pub unsafe fn {}({}) {} {{",
        name, args_decl_str, return_annotation
    )?;

    // We don't need FnType for syscalls, we just need the SSN
    writeln!(output)?;
    writeln!(output, "    static mut SSN: u16 = 0;")?;
    writeln!(
        output,
        "    static INIT: std::sync::Once = std::sync::Once::new();"
    )?;
    writeln!(output)?;
    writeln!(output, "    INIT.call_once(|| {{")?;

    // Only works for NTDLL, but we keep 'dll' variable for flexibility if needed
    // In practice, Hell's Gate is strictly for "NTDLL.DLL"
    writeln!(
        output,
        "        if let Ok(module) = NativePERuntime::from_module(\"{}\") {{",
        dll
    )?;
    writeln!(
        output,
        "            if let Ok(export) = module.find_export(\"{}\") {{",
        target_func
    )?;
    writeln!(
        output,
        "                if let Ok(s) = module.get_syscall_num(export) {{"
    )?;
    writeln!(output, "                    unsafe {{ SSN = s; }}")?;
    writeln!(output, "                }}")?;
    writeln!(output, "            }}")?;
    writeln!(output, "        }}")?;
    writeln!(output, "    }});")?;
    writeln!(output)?;

    // Invocation via the syscall! macro
    // We explicitly cast the result to the expected return type
    let invocation_args = if arg_names_str.trim().is_empty() {
        String::new()
    } else {
        format!(", {}", arg_names_str) // format args as: arg1, arg2
    };

    writeln!(
        output,
        // Remove the hardcoded comma after SSN used in the template
        "    crate::syscall!(unsafe {{ SSN }}{}) as {}",
        invocation_args, return_type_str
    )?;
    writeln!(output, "}}")?;
    writeln!(output)?;

    Ok(())
}

fn generate_single_wrapper(
    output: &mut File,
    name: &str,
    real_func_name: Option<&str>, // Added parameter
    args_decl_str: &str,
    return_annotation: &str,
    arg_names_str: &str,
    fn_type_args_str: &str,
    return_type_str: &str,
    dll: &str,
) -> std::io::Result<()> {
    let target_func = real_func_name.unwrap_or(name);

    // Normal version
    writeln!(output, "#[cfg(not(feature = \"obfuscation\"))]")?;
    writeln!(output, "#[inline]")?;
    writeln!(
        output,
        "pub unsafe fn {}({}) {} {{",
        name, args_decl_str, return_annotation
    )?;
    writeln!(
        output,
        "    unsafe {{ raw::{}({}) }} ",
        target_func, arg_names_str
    )?;
    writeln!(output, "}}")?;
    writeln!(output)?;

    // Obfuscated version
    writeln!(output, "#[cfg(feature = \"obfuscation\")]")?;
    writeln!(
        output,
        "pub unsafe fn {}({}) {} {{",
        name, args_decl_str, return_annotation
    )?;
    writeln!(
        output,
        "    type FnType = unsafe extern \"system\" fn({}) -> {};",
        fn_type_args_str, return_type_str
    )?;
    writeln!(output)?;
    writeln!(output, "    static mut FN_PTR: Option<FnType> = None;")?;
    writeln!(
        output,
        "    static INIT: std::sync::Once = std::sync::Once::new();"
    )?;
    writeln!(output)?;
    writeln!(output, "    INIT.call_once(|| {{")?;

    if dll.to_uppercase() != "KERNEL32.DLL" {
        writeln!(
            output,
            "        let _ = LoadLibraryW((to_wide(\"{}\")).as_ptr());",
            { dll }
        )?;
    }
    writeln!(
        output,
        "        if let Ok(module) = NativePERuntime::from_module(\"{}\") {{",
        dll
    )?;
    writeln!(
        output,
        "            if let Ok(export) = module.find_export(\"{}\") {{",
        target_func
    )?;
    writeln!(
        output,
        "                unsafe {{ FN_PTR = Some(core::mem::transmute(export.func_addr as usize) ); }}"
    )?;
    writeln!(output, "            }}")?;
    writeln!(output, "        }}")?;
    writeln!(output, "    }});")?;
    writeln!(output)?;
    writeln!(
        output,
        "   unsafe{{ FN_PTR.expect(\"Failed to load {}\")({}) }}",
        name, arg_names_str
    )?;
    writeln!(output, "}}")?;
    writeln!(output)?;

    Ok(())
}

fn type_to_string(ty: &syn::Type) -> String {
    match ty {
        syn::Type::Path(type_path) => {
            // Handle full path with generics
            let segments = &type_path.path.segments;
            segments
                .iter()
                .map(|seg| {
                    let ident = seg.ident.to_string();

                    // Handle generic arguments
                    match &seg.arguments {
                        syn::PathArguments::None => ident,
                        syn::PathArguments::AngleBracketed(args) => {
                            let generic_args = args
                                .args
                                .iter()
                                .map(|arg| match arg {
                                    syn::GenericArgument::Type(ty) => type_to_string(ty),
                                    syn::GenericArgument::Lifetime(lt) => format!("'{}", lt.ident),
                                    syn::GenericArgument::Const(expr) => {
                                        quote::quote!(#expr).to_string()
                                    }
                                    _ => String::new(),
                                })
                                .filter(|s| !s.is_empty())
                                .collect::<Vec<_>>()
                                .join(", ");
                            format!("{}<{}>", ident, generic_args)
                        }
                        syn::PathArguments::Parenthesized(args) => {
                            let inputs = args
                                .inputs
                                .iter()
                                .map(type_to_string)
                                .collect::<Vec<_>>()
                                .join(", ");
                            let output = match &args.output {
                                syn::ReturnType::Default => String::new(),
                                syn::ReturnType::Type(_, ty) => {
                                    format!(" -> {}", type_to_string(ty))
                                }
                            };
                            format!("{}({}){}", ident, inputs, output)
                        }
                    }
                })
                .collect::<Vec<_>>()
                .join("::")
        }
        syn::Type::Ptr(type_ptr) => {
            let mutability = if type_ptr.mutability.is_some() {
                "mut "
            } else {
                "const "
            };
            format!("*{}{}", mutability, type_to_string(&type_ptr.elem))
        }
        syn::Type::Reference(type_ref) => {
            let mutability = if type_ref.mutability.is_some() {
                "mut "
            } else {
                ""
            };
            let lifetime = type_ref
                .lifetime
                .as_ref()
                .map(|lt| format!("'{} ", lt.ident))
                .unwrap_or_default();
            format!(
                "&{}{}{}",
                lifetime,
                mutability,
                type_to_string(&type_ref.elem)
            )
        }
        syn::Type::Array(type_array) => {
            format!(
                "[{}; {}]",
                type_to_string(&type_array.elem),
                quote::quote!(#type_array.len)
            )
        }
        syn::Type::Tuple(type_tuple) => {
            if type_tuple.elems.is_empty() {
                "()".to_string()
            } else {
                let elems = type_tuple
                    .elems
                    .iter()
                    .map(type_to_string)
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("({})", elems)
            }
        }
        syn::Type::BareFn(bare_fn) => {
            // Function pointer type
            let unsafety = if bare_fn.unsafety.is_some() {
                "unsafe "
            } else {
                ""
            };
            let abi = bare_fn
                .abi
                .as_ref()
                .map(|abi| format!("extern \"{}\" ", abi.name.as_ref().unwrap().value()))
                .unwrap_or_default();

            let inputs = bare_fn
                .inputs
                .iter()
                .map(|arg| {
                    let name = arg
                        .name
                        .as_ref()
                        .map(|(ident, _)| format!("{}: ", ident))
                        .unwrap_or_default();
                    format!("{}{}", name, type_to_string(&arg.ty))
                })
                .collect::<Vec<_>>()
                .join(", ");

            let output = match &bare_fn.output {
                syn::ReturnType::Default => String::new(),
                syn::ReturnType::Type(_, ty) => format!(" -> {}", type_to_string(ty)),
            };

            format!("{}{}fn({}){}", unsafety, abi, inputs, output)
        }
        _ => {
            // Fallback: use quote
            quote::quote!(#ty).to_string()
        }
    }
}

fn guess_dll(func_name: &str) -> &'static str {
    let name_lower = func_name.to_lowercase();

    // Check prefixes first
    if name_lower.starts_with("zw") || name_lower.starts_with("nt") {
        return "NTDLL.DLL";
    }

    // Match based on keywords
    match () {
        _ if name_lower.contains("process")
            || name_lower.contains("thread")
            || name_lower.contains("library")
            || name_lower.contains("module")
            || name_lower.contains("toolhelp")
            || name_lower.contains("heap")
            || name_lower.contains("virtual")
            || name_lower.contains("createfile") =>
        {
            "KERNEL32.DLL"
        }

        _ if name_lower.contains("window")
            || name_lower.contains("message")
            || name_lower.contains("dialog")
            || name_lower.contains("menu")
            || name_lower.contains("input")
            || name_lower.contains("foreground")
            || name_lower.contains("hook") =>
        {
            "USER32.DLL"
        }

        _ if name_lower.contains("reg")
            || name_lower.contains("security")
            || name_lower.contains("service") =>
        {
            "ADVAPI32.DLL"
        }

        _ if name_lower.contains("gdi")
            || name_lower.contains("bitmap")
            || name_lower.contains("brush") =>
        {
            "GDI32.DLL"
        }

        _ if name_lower.contains("shell") || name_lower.contains("shget") => "SHELL32.DLL",

        _ => "KERNEL32.DLL",
    }
}
