[package]
name = "libwinexploit"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
env_logger = "0.11.8"
log = "0.4.29"
memchr = "2.8.0"
obfstr = {version= "0.4.4", optional = true}
thiserror = "2.0.17"
windows-sys = { version = "0.61.2", features = ["Win32_System_Diagnostics_ToolHelp","Win32_System_Threading","Win32_System_ProcessStatus","Win32_System_WindowsProgramming", "Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_System_Threading", "Win32_UI_WindowsAndMessaging", "Win32_Data", "Win32_System_LibraryLoader", "Win32_System_Kernel"] }


[features]
default = ["runtime","obfuscation","hells_gate"]
obfuscation = ["dep:obfstr","runtime"]
runtime = []
hells_gate = ["runtime"]

[[bin]]
name = "get_remote_dlls_winapi"
path = "src/bin/get_remote_dlls_winapi.rs"
required-features = ["runtime"]

[[bin]]
name = "get_self_dlls"
path = "src/bin/get_self_dlls.rs"
required-features = ["runtime"]

[[bin]]
name = "hells_gate"
path = "src/bin/hells_gate.rs"
required-features = ["hells_gate"]

[[bin]]
name = "hells_gate_auto_binded"
path = "src/bin/hells_gate_auto_binded.rs"
required-features = ["hells_gate"]

[[bin]]
name = "hells_query_systime"
path = "src/bin/hells_query_systime.rs"
required-features = ["hells_gate"]

[[bin]]
name = "hook"
path = "src/bin/hook.rs"
required-features = ["runtime"]

[[bin]]
name = "hookpattern"
path = "src/bin/hookpattern.rs"
required-features = ["runtime"]

[[bin]]
name = "process"
path = "src/bin/process.rs"
required-features = ["runtime"]

[[bin]]
name = "read_pe_file"
path = "src/bin/read_pe_file.rs"
required-features = ["runtime"]

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = false
overflow-checks = false
incremental = false
rpath = false

[build-dependencies]
mfa = { git = "https://github.com/natimerry/pocket", version = "0.1.0"}
bindgen = "0.70"
syn = { version = "2.0", features = ["full", "parsing"] }
quote = "1.0"
indicatif = "0.17"

[target.'cfg(windows)'.build-dependencies]
winreg = "0.55.0"


[profile.dev]
incremental = true
codegen-units = 16
