[package]
name = "libwinexploit"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
obfstr = {version= "0.4.4", optional = true}
thiserror = "2.0.17"
windows-sys = { version = "0.61.2", features = ["Win32_System_Diagnostics_ToolHelp","Win32_System_Threading","Win32_System_ProcessStatus","Win32_System_WindowsProgramming", "Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_System_Threading", "Win32_UI_WindowsAndMessaging", "Win32_Data", "Win32_System_LibraryLoader", "Win32_System_Kernel"] }


[features]
default = ["runtime","obfuscation","hells_gate"]
obfuscation = ["dep:obfstr","runtime"]
runtime = []
hells_gate = []

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = false
overflow-checks = false
incremental = false
rpath = false

[build-dependencies]
mfa = { git = "https://github.com/natimerry/pocket", version = "0.1.0"}
bindgen = "0.70"
syn = { version = "2.0", features = ["full", "parsing"] }
quote = "1.0"
indicatif = "0.17"


[profile.dev]
incremental = true
codegen-units = 16
