imports_granularity = "Item"
group_imports = "One"
reorder_imports = true
reorder_modules = true
normalize_comments = true
comment_width = 80
wrap_comments = true
use_field_init_shorthand = true
fn_single_line = true
type_punctuation_density = "Wide"
