[package]
name = "glazier-winapi"
version = "0.1.0"
edition = "2024"

[features]
default = []
obfuscation = ["dep:glazier-runtime"]
hells_gate = ["dep:glazier-runtime"]

[dependencies]
glazier-bindings = { path = "../bindings" }
glazier-runtime = { path = "../runtime", optional = true }

[build-dependencies]
glazier-codegen = { path = "../codegen" }
